---
title: "QAQC Workshop - Fuels Duff Litt"
author: "FFI + R Working Group"
date: "2024-11-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

# Install packages (if needed)
#install.packages("tidyverse")
```

# BEFORE STARTING

### Load Packages

```{r}
# Load packages

# tidyverse and dplyr have lots of useful functions for data cleaning
library(tidyverse)
library(dplyr)
# writexl is used to create excel files from within R
library(writexl)
# knitr is used to create output files from R Markdown
library(knitr)
# EnvStats is needed for the rosnerTest() function
library(EnvStats)
```

### Adjust File Paths

Make sure to update file paths to be specific for your data.

```{r}
# Identify working directory
getwd()

# Load in data. Change file path based on user name!
path_data <- "C:/Users/alalor.NPS/OneDrive - DOI/Desktop/Workshop1_QAQC/data/"
path_errors <- "C:/Users/alalor.NPS/OneDrive - DOI/Desktop/Workshop1_QAQC/output/"
```

### Load Data

```{r}
# Load in data
FuelsDuffLitt_all <- read.csv(paste0(path_data, "GRCA_Surface Fuels - Duff_Litter_XPT.csv"))
```

```{r}
# Clean up data frame
FuelsDuffLitt_all <- FuelsDuffLitt_all %>%
  # Separate Date column into Date and Time columns
  separate(Date, sep = " ", into = c("Date", "Time")) %>%
  separate(Date, sep = "/", into = c("Month", "Day", "Year"), remove = FALSE) %>% 
  select(!c("Month", "Day")) %>% 
  # Separate MacroPlotName to get Monitoring type
  separate(MacroPlot.Name, sep = " ", into = c("MonitoringType", "Plot"), remove = FALSE)

# Ensure blanks in Visited column are NA
FuelsDuffLitt_all$Visited[FuelsDuffLitt_all$Visited==""] <- NA

# Filter for only data
FuelsDuffLitt_data <- FuelsDuffLitt_all %>%
  filter(is.na(Visited), Year == 2024)

# Filter for only headers
FuelsDuffLitt_header <- FuelsDuffLitt_all %>%
  filter(!is.na(Visited), Year == 2024)
```

### Create blank data frame

```{r}
# Blank data frame for no errors
errors_blank <- data.frame("SavedQuery" = "",
                           "MacroPlot.Name" = "",
                           "Date" = "",
                           "Error" = "No Error", 
                           "Comment" = "")
```

### Create Functions

```{r}
# QAQC function
qaqc <- function(data, query, query_message, values_check) {
  # Identify errors 
  errors <- data %>%   
    mutate("SavedQuery" = query, 
           "Error" = paste(query_message, "=", values_data)) %>%
    filter(!(values_check) %>% replace_na(TRUE)) %>%   
    select("SavedQuery", "MacroPlot.Name", "Date", "Error", "Comment")
  
  # If no errors, add "No Errors" to existing data frame 
  if (nrow(errors) == 0) {   
    errors <- errors_blank %>%     
      mutate(SavedQuery = query) 
  } else {   
    errors <- errors
  }
}
```
